update minios-installer

diff --git a/minios-installer b/minios-installer
--- a/minios-installer
+++ b/minios-installer
@@ -186,40 +186,38 @@ install_boot_record() {
 }
 
 # Perform the MiniOS installation process
-install_minios() {
-    (
-        echo "0"
-        umount_part
-        echo "5"
-        wipe_disk
-        echo "10"
-        echo "$(translate "Creating a new partition on disk $PART...")"
-        partition_disk
-        echo "15"
-        echo "$(translate "Formatting disk $PART with MBR partition table and") $FS $(translate "file system...")"
-        format_partition
-        echo "20"
-        echo "$(translate "Mounting the new partition on disk $PART...")"
-        mount_part
-        echo "25"
-        echo "$(translate "Copying MiniOS files to the new partition on disk $PART...")"
-        copy_files
-        echo "90"
-        echo "$(translate "Running the MiniOS boot installer on disk $PART...")"
-        install_boot_record
-        echo "95"
-        umount_part
-        echo "100"
-    ) | yad --progress --title="$(translate "Installing MiniOS")" --text="$(translate "Starting installation of MiniOS on disk $PART...")" --auto-close --auto-kill
-    echo $FAILED
-    if [ "$FAILED" != "true" ]; then
-        yad --info --title="$(translate "Installation Complete")" --text="$(translate "Installation of MiniOS on disk") $PART $(translate "has been completed successfully.")" --no-wrap
-    else
-        yad --error --title="$(translate "Error")" --text="$(translate "An error occurred during the installation of MiniOS on disk") $PART ."
-    fi
-    final_question
+show_error_message() {
+    local error_message="$1"
+    yad --error --title="$(translate "Error")" --text="$(translate "An error occurred while executing the function.")"
+    exit 1
 }
 
+# Perform the MiniOS installation process
+install_minios() {
+        echo "0"
+        umount_part || show_error_message
+        echo "5"
+        wipe_disk || show_error_message
+        echo "10"
+        echo "$(translate "Creating a new partition on disk $PART...")"
+        partition_disk || show_error_message
+        echo "15"
+        echo "$(translate "Formatting disk $PART with MBR partition table and") $FS $(translate "file system...")"
+        format_partition || show_error_message
+        echo "20"
+        echo "$(translate "Mounting the new partition on disk $PART...")"
+        mount_part || show_error_message
+        echo "25"
+        echo "$(translate "Copying MiniOS files to the new partition on disk $PART...")"
+        copy_files || show_error_message
+        echo "90"
+        echo "$(translate "Running the MiniOS boot installer on disk $PART...")"
+        install_boot_record || show_error_message
+        echo "95"
+        umount_part || show_error_message
+        echo "100"
+        final_question
+}
 # Display the main menu for selecting installation options
 main_menu() {
     list_disks
@@ -255,7 +253,7 @@ main_menu() {
         exit 0
         ;;
     102)
-        install_minios
+        install_minios | yad --progress --title="$(translate "Process")" --text="$(translate "Iniciando...")" --auto-close --auto-kill
         ;;
     103)
         main_menu
